# This is a list of video configurations
- video_url: "rtsp://example1.com/stream"  # URL of the video
  site: "Construction Site"  # Location of the monitoring system
  stream_name: "Front Gate"  #  Number of the camera
  model_key: "yolo11n"  # Model key for the video
  notifications:  # List of line tokens, and languages for notifications
    line_token_1: language_1
    line_token_2: language_2
  detect_with_server: True  # Run objection detection with server
  expire_date: "2024-12-31T23:59:59"  # Expire date in ISO 8601 format
- video_url: "streaming URL"  # Streaming URL of the video
  site: "Factory_1"  # Location of the monitoring system
  stream_name: "camera_1"  # Number of the camera
  model_key: "yolo11n"  # Model key for detection
  notifications:  # List of line tokens, and languages for notifications
    line_token_3: language_3
    line_token_4: language_4
  detect_with_server: False  # Run objection detection in local
  expire_date: "No Expire Date"  # String for no expire date
