name: Workflow for Codecov example-python

permissions:
  contents: read

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Update and upgrade apt-get
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get autoremove -y
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download model weights (Hugging Face)
        run: |
          hf download \
            yihong1120/Construction-Hazard-Detection-YOLO11 \
            --repo-type model \
            --include "models/pt/*.pt" \
            --local-dir .
      - name: Run tests and collect coverage
        run: |
          # Measure only application code (main, src, examples); exclude tests from coverage sources
          pytest \
            --cov=main \
            --cov=src \
            --cov=examples \
            --cov-report=term-missing \
            --cov-report=xml \
            -n auto \
            tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
